# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    desc: 'Build the extension'
    cmds:
      - yarn build

  add-dev-extension:
    desc: 'Install/Update dist/ to user directory for development'
    # deps: [build]
    cmds:
      - rsync -av --delete dist/ ~/.local/share/gnome-shell/extensions/pano-gom@txlab.io/

  remove-dev-extension:
    desc: 'Remove extension from user directory'
    cmds:
      - rm -rf ~/.local/share/gnome-shell/extensions/pano-gom@txlab.io

  dev:
    desc: 'Build and test extension in nested GNOME Shell session'
    deps: [add-dev-extension]
    cmds:
      - ./test-nested.nu nested
